force-app/main/notification/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NTF-{000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/notification/objects/Notification__c/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <label>Icon Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/notification/objects/Notification__c/fields/Is_Read__c.field-meta.xml
<CustomField>
    <fullName>Is_Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Read?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/notification/objects/Notification__c/fields/Notified_User__c.field-meta.xml
<CustomField>
    <fullName>Notified_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notified User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/notification/objects/Notification__c/fields/Related_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Related Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/notification/objects/Notification__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/notification/objects/Notification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>KYC</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/notification/classes/MyNotificationsController.cls
public with sharing class MyNotificationsController {
    @AuraEnabled
    public static List<Notification__c> getLoginUserNotifications() {
        return [SELECT Id, Title__c, Body__c, Type__c, CreatedDate, Related_Record_Id__c, Icon_Name__c, Is_Read__c FROM Notification__c WHERE Notified_User__c = :UserInfo.getUserId() ORDER BY CreatedDate DESC];
    } 
    
    @AuraEnabled
    public static Id getLoginUserId() {
        return UserInfo.getUserId();
    }
    
    @AuraEnabled
    public static Boolean markReadNotifications(List<Id> notificationIdList) {
        Boolean ret = false;
        List<Notification__c> notificationList = new List<Notification__c>();
        for(Id oneNtfId : notificationIdList) {
            notificationList.add(new Notification__c(Id = oneNtfId, Is_Read__c = true));
        }
        update notificationList;
        ret = true;
        return ret;
    } 
}